@host=https://localhost:7130

### Create Appointment
POST {{host}}/api/appointment
Content-Type: application/json

{
    "StartYear": 2023,
    "StartMonth": 12,
    "StartDay": 30,
    "StartHour": 14,
    "StartMinute": 30,
    "EndYear": 2023,
    "EndMonth": 11,
    "EndDay": 20,
    "EndHour": 15,
    "EndMinute": 30
}

### Update Appointment
PUT {{host}}/api/appointment/1
Content-Type: application/json

{
    "StartYear": 2023,
    "StartMonth": 11,
    "StartDay": 21,
    "StartHour": 10,
    "StartMinute": 0,
    "EndYear": 2023,
    "EndMonth": 11,
    "EndDay": 21,
    "EndHour": 23,
    "EndMinute": 0
}
